# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6684e1b4360e7924f9c27c3b19c80794d32a08075deeed33776a2436406cb54a17de56b84f7fff0273d1d06b803dd4b8c8ad4bd9b77b670d1d81dcb3c435a320

test:
  secret_key_base: 234ac6a44e892a1abe36a4fdfa833fd367305a607fb34e9ff68f23ac9906dad582790221fe4ee788aab717eb2b6ab5b34ef06cfaaae54f53e4eb405616cef722

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
